name: flutter_blue_plus
description: Flutter plugin for connecting and communicationg with Bluetooth Low Energy devices, on Android, iOS, and MacOS.
version: 1.33.5
homepage: https://github.com/boskokg/flutter_blue_plus

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  bluetooth_low_energy: ^6.0.2
  flutter:
    sdk: flutter
  flutter_foreground_task: ^8.13.0
  sqflite: ^2.4.2

flutter:
  plugin:
    platforms:
      android:
        package: com.lib.flutter_blue_plus
        pluginClass: FlutterBluePlusPlugin
      ios:
        pluginClass: FlutterBluePlusPlugin
      macos:
        pluginClass: FlutterBluePlusPlugin
